export const motivationalQuotes = [
  "Success is not final, failure is not fatal: It is the courage to continue that counts. Every step you take, no matter how small, is progress toward your goal. Keep pushing forward, especially when it feels hardest.",
  "When you feel like quitting, remember why you started. Every expert was once a beginner, and the path to mastery is walked step by determined step. Don’t stop—your future self will thank you.",
  "You are capable of more than you know. Don't limit yourself with doubt. Break through that mental barrier and discover the strength within you to go beyond what you imagined.",
  "There will be days when you feel like giving up, but those are the days you must dig deeper and remind yourself that growth lives outside of comfort. Keep going—breakthrough is near.",
  "The journey to success is often slow and invisible. But just like seeds buried in soil, your efforts are growing roots. Stay consistent, and in time, the bloom will come.",
  "You don’t have to be perfect to be powerful. Your progress, with all its stumbles, is a testament to your resilience. Show up for yourself—every single day.",
  "Everything you’re learning now—every skill, every late night, every challenge—will one day be the foundation for your success. Don’t waste the struggle; use it.",
  "Discipline is doing what needs to be done, even when you don’t feel like it. Motivation gets you started, but habits keep you going. Build those habits brick by brick.",
  "Remember, you are writing your own story. Today is a page. Make it one of courage, effort, and forward motion. Someday, this chapter will be the one you’re proudest of.",
  "There is no shortcut to greatness. Every skill you develop, every late hour you spend learning, every time you choose growth over comfort—it’s all adding up. Trust the process.",
  "It’s not about how fast you get there. It’s about staying in the race long enough to cross the finish line. Slow progress is still progress. Don’t give up.",
  "Your current struggles are carving the strength you’ll need for your future victories. Let each difficulty be a lesson, and each setback, a setup for something greater.",
  "You weren’t born to stay stagnant. You’re meant to stretch, to reach, to fall, to rise, and to evolve. Every mistake is part of your metamorphosis. Embrace the process.",
  "Your dreams don’t work unless you do. But you don’t have to be loud. Quietly keep working. Quietly stay consistent. And quietly watch your life transform.",
  "Sometimes success is just showing up—again and again. When others give up, let your presence, your effort, and your heart set you apart.",
  "Your dreams are valid, even if no one else sees them. Keep nurturing them in silence, and let the results speak volumes when the time is right.",
  "The people you admire once stood where you stand now—unsure, learning, doubting. But they chose not to quit. That’s what made the difference. You can make that choice too.",
  "Don’t let fear of failure stop you. Let it fuel you. You are not here to blend in—you are here to stand out, to build, to rise. Let the fire in you burn brighter than your doubts.",
  "You will never regret the time you spent bettering yourself. Each day you rise and try again, you move further from who you were and closer to who you’re meant to be.",
  "You don’t have to have it all figured out. You just need to take the next right step. Trust that clarity will come with motion. Keep stepping forward.",
  "In a world full of distractions, staying focused is a superpower. Guard your goals. Protect your peace. And work quietly until your life becomes your loudest statement.",
  "Start where you are. Use what you have. Do what you can. The magic is not in perfection—it’s in persistence, in showing up even when it’s hard.",
  "Let your vision be stronger than your obstacles. If the road is hard, it means you’re going somewhere worth reaching. Don’t stop now—you’ve already come too far.",
  "The grind will be lonely. You’ll doubt yourself. You’ll wonder if it’s worth it. But when you look back at who you’ve become because of it—you’ll realize it was everything.",
  "Don’t underestimate small steps. Brick by brick, habit by habit, you’re building a foundation no one can take from you. Keep laying those bricks.",
  "Your effort is never wasted. Even the days when you feel like you achieved nothing, you built grit. You trained resilience. That counts too. Keep going.",
  "Be patient with yourself. Learning and growing is messy work. Celebrate your effort. Honor your progress. And above all, never talk yourself out of your dreams.",
  "Success isn’t a moment—it’s a series of consistent choices. Choose growth. Choose grit. Choose the version of yourself that doesn’t give up.",
  "There are no overnight successes. Just people who showed up, worked hard, failed, tried again, and kept going when others quit. Be one of them.",
  "Learning something new is like planting a tree. You may not see growth right away, but roots are forming. Stick with it. Growth is happening.",
  "Every hour spent learning, practicing, or creating is an investment. You’re building a future where your current self will look back and say: 'Thank you for not quitting.'",
  "There will always be reasons to stop. You only need one good reason to keep going. Let your future self be that reason.",
  "Rest when you need to, but never quit. Progress is not linear. Your effort matters, even when the results are not yet visible.",
  "You don’t need to feel confident to act. You just need to be brave enough to begin. Confidence will follow action.",
  "You are not behind. You are on your own timeline. Don’t compare your path—just make sure you’re still moving forward.",
  "Not everyone will understand your vision. That’s okay. It was given to you, not them. Keep building quietly.",
  "Hard work beats talent when talent doesn’t work hard. Stay focused. Stay hungry. Your effort will speak for you.",
  "The goal isn’t to avoid failure. It’s to keep failing forward. Each mistake brings you closer to mastery. Fail. Learn. Repeat.",
  "You’re not doing this for applause. You’re doing this for your growth, your future, your freedom. Keep your eyes on that.",
  "The difference between those who succeed and those who don’t isn’t ability—it’s determination. Choose to keep going, no matter what.",
  "Doubt kills more dreams than failure ever will. Believe in the possibility, even if the path is unclear. Your belief is the first step.",
  "Each new day is another chance to move closer to your dreams. Don’t waste the opportunity. Start small, but start.",
  "Let this be the season where you prove to yourself that you can do hard things. Let this be the season you rise.",
  "What you’re doing today may feel small, but it’s preparing you for something much bigger. Don’t dismiss the small steps.",
  "Consistency compounds. Show up, do the work, stay focused. In time, those small efforts will become your biggest wins.",
  "Keep going, not because it's easy—but because it's worth it. Your discipline will build the life your motivation promised.",
  "There’s a reason you started. Don’t let temporary emotion make you forget your permanent purpose.",
  "You may not feel strong every day, but every time you choose effort over excuse, you’re becoming stronger than you know.",
  "Growth doesn't come from comfort. Every challenge you face is shaping you into someone stronger, wiser, and more capable than before.",
  "Even when progress seems invisible, your persistence is creating ripples. Trust that every effort is moving you closer to your goal.",
  "You may not see results today, but every step you take builds a foundation for the success you’re striving for tomorrow.",
  "Remember, failure isn't the opposite of success—it's part of it. Keep learning, keep growing, and don’t quit.",
  "Success is not reserved for the extraordinary. It belongs to those who are willing to keep going, even when it gets tough.",
  "Don't underestimate the power of consistency. Small, repeated actions often lead to the biggest results.",
  "Your journey might be long, and the path might be rough, but you have everything it takes to finish strong.",
  "When you feel like quitting, remind yourself why you started. Your purpose is stronger than any excuse.",
  "Even slow progress is progress. Celebrate the small wins—they're the building blocks of big achievements.",
  "The struggle you're facing today is shaping the strength you'll rely on tomorrow. Keep pushing forward.",
  "Rest when you're tired, but never quit. The vision you have is still worth chasing.",
  "You don’t have to get it perfect. You just have to get it going. Start where you are and refine as you move.",
  "It's okay to have bad days. It’s okay to feel stuck. Just don’t stay there. You have the power to begin again.",
  "You are not behind. You are on a unique timeline that cannot be measured by anyone else's progress.",
  "Your potential is limitless. The only thing standing in your way is the belief that you’ve reached your limit.",
  "If it matters to you, don’t stop. Keep showing up, even when it feels like no one notices—because you’ll notice the difference.",
  "The people you admire once stood where you are—uncertain, inexperienced, and afraid. They kept going. So can you.",
  "Doubt will whisper. Fear will shout. But your action can silence them both.",
  "Don’t wait for motivation. Let discipline carry you when inspiration fades. That’s how progress is made.",
  "If you're still dreaming about it, it's not over. As long as it's in your heart, it’s worth fighting for.",
  "Hard days are part of the path. But remember, you are not your bad moments. You are your resilience.",
  "The desire to give up is often strongest right before a breakthrough. Hang in there just a little longer.",
  "Every expert was once a beginner who didn’t quit. Embrace the process of becoming.",
  "When you commit to something, the universe begins to align things in your favor. Stay committed.",
  "You were built for more than survival. You were built for growth, for excellence, for impact.",
  "Don’t compare your chapter 2 to someone else’s chapter 20. Your story is still unfolding.",
  "Progress is rarely loud. It’s the quiet decisions you make daily that shape your future.",
  "Your time is too valuable to spend on self-doubt. Believe in your ability to figure things out.",
  "When the weight feels too heavy, remember the strength you've already built. You’ve carried more than this before.",
  "Keep going—not because it’s easy, but because you’re capable and your dreams are valid.",
  "The version of you who started this journey would be so proud of how far you’ve come. Keep moving.",
  "You’re not falling behind—you’re laying bricks. One at a time, you're building something meaningful.",
  "You don't need a perfect plan to start. What matters most is that you begin.",
  "There’s power in showing up—especially on the days you don't feel like it. That’s where character is built.",
  "What you’re learning now might not seem useful yet—but one day, it’ll be exactly what you need.",
  "Success rarely comes overnight. It comes from every late night, every retry, and every refusal to quit.",
  "You won’t always feel motivated, but you can always choose to keep going. That’s how greatness is built.",
  "Be patient with your journey. Mastery takes time, and true growth cannot be rushed.",
  "You are capable of so much more than you realize. Keep showing up until you believe it too.",
  "You are doing better than you think. Sometimes the fact that you're still trying is the biggest win.",
  "Your purpose doesn’t expire. No matter how long it takes, it’s still worth pursuing.",
  "The road to success is paved with doubt, failure, and fear. Walk it anyway.",
  "If you're tired, take a breath—but don’t give up. Your future self is cheering you on.",
  "Skill is earned in silence. Mastery is built in the shadows. Keep going—your moment will come.",
  "When it feels overwhelming, break it down. One task. One hour. One more step. You’ve got this.",
  "You’re not too late, too old, or too far behind. You are exactly where you need to be to begin.",
  "What you’re doing today might seem small, but one day you’ll look back and realize it was everything.",
  "Courage isn’t the absence of fear—it’s the decision to move forward anyway.",
  "No storm lasts forever. If you’re in the middle of one, just keep moving. Brighter days are ahead.",
];
